### ISSUE TITLE
error: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39

### ISSUE THREAD

**Issue by chopshop1** [JPZ13/dpm#37]
When I try running the app I get this error:
<img width="872" alt="Screen Shot 2019-08-26 at 9 46 24 AM" src="https://user-images.githubusercontent.com/14365735/63695393-9c49d280-c7e6-11e9-866a-2ad8234be983.png">

**Comment by JPZ13** [comment]
@Amad27 This one is fixable on your local machine. Add `export DOCKER_API_VERSION=1.39` to your `.zshrc` and source your `.zshrc`. Let me know if it works after that

**Comment by JPZ13** [comment]
I'll work on smoothing out the installation to have fewer steps, but the above environment variable should get you by in the meantime.

**Comment by chopshop1** [comment]
That worked. Thanks!
